/**
 * =================================================================================================
 * FILE: button.tsx
 * =================================================================================================
 *
 * @description A customizable button component based on shadcn/ui.
 *
 * @layer components/ui
 *
 * @purpose This component provides a highly reusable and stylable button. It uses
 *          `class-variance-authority` (CVA) to manage different visual variants (like `default`,
 *          `destructive`, `outline`) and sizes. It also includes the `asChild` prop, a powerful
 *          pattern from Radix UI that allows the button's styles and properties to be applied
 *          to a child component.
 *
 * @see https://www.radix-ui.com/docs/primitives/utilities/slot for `asChild` prop documentation.
 * @see https://cva.style/docs for `class-variance-authority` documentation.
 * =================================================================================================
 */

// =================================================================================================
// IMPORTS
// =================================================================================================
import * as React from 'react';
import { Slot } from '@radix-ui/react-slot';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '@/lib/utils';

// =================================================================================================
// VARIANTS
// =================================================================================================
/**
 * @const buttonVariants
 * @description Defines the CSS classes for the button's different styles and sizes using CVA.
 *
 * @param {string} baseClasses - The first argument to `cva` provides the base classes that are
 *        applied to all variants. This includes styles for flex layout, transitions, focus rings,
 *        and disabled states.
 * @param {object} options - The second argument contains the configuration for variants.
 *  - `variants`: An object where each key (`variant`, `size`) represents a category of styles.
 *    Each category contains different options (`default`, `destructive`, etc.) and their
 *    corresponding Tailwind CSS classes.
 *  - `defaultVariants`: Specifies the default `variant` and `size` to be used if they are not
 *    explicitly provided as props to the component.
 */
const buttonVariants = cva(
  'inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50',
  {
    variants: {
      variant: {
        default: 'bg-primary text-primary-foreground hover:bg-primary/90',
        destructive:
          'bg-destructive text-destructive-foreground hover:bg-destructive/90',
        outline:
          'border border-input bg-background hover:bg-accent hover:text-accent-foreground',
        secondary:
          'bg-secondary text-secondary-foreground hover:bg-secondary/80',
        ghost: 'hover:bg-accent hover:text-accent-foreground',
        link: 'text-primary underline-offset-4 hover:underline',
      },
      size: {
        default: 'h-10 px-4 py-2',
        sm: 'h-9 rounded-md px-3',
        lg: 'h-11 rounded-md px-8',
        icon: 'h-10 w-10',
      },
    },
    defaultVariants: {
      variant: 'default',
      size: 'default',
    },
  }
);

// =================================================================================================
// INTERFACE & COMPONENT
// =================================================================================================
/**
 * @interface ButtonProps
 * @extends React.ButtonHTMLAttributes<HTMLButtonElement>
 * @extends VariantProps<typeof buttonVariants>
 *
 * @property {boolean} [asChild=false] - If true, the component will render its child and pass
 *           the button properties and styles to it. This is useful for wrapping other components,
 *           like a Next.js `<Link>`, and making them look and behave like a button.
 */
export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  asChild?: boolean;
}

/**
 * @function Button
 * @description The main button component.
 *
 * @param {ButtonProps} props - The component props.
 * @param {React.Ref<HTMLButtonElement>} ref - Forwarded ref to the underlying button element.
 *
 * @logic
 * 1. **Determine Component Type:** It checks the `asChild` prop.
 *    - If `asChild` is `true`, `Comp` is set to `Slot`. `Slot` is a special component from
 *      Radix UI that merges its props onto its immediate child.
 *    - If `asChild` is `false` (the default), `Comp` is set to a standard HTML `'button'` string.
 * 2. **Combine Classes:** It uses the `cn` utility to merge the classes generated by
 *    `buttonVariants` with any additional `className` passed in the props.
 * 3. **Render Component:** It renders the `Comp` (either `Slot` or `'button'`), passing down the
 *    combined class names, the forwarded ref, and all other props.
 */
const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, asChild = false, ...props }, ref) => {
    const Comp = asChild ? Slot : 'button';
    return (
      <Comp
        className={cn(buttonVariants({ variant, size, className }))}
        ref={ref}
        {...props}
      />
    );
  }
);
Button.displayName = 'Button';

export { Button, buttonVariants };
